### ISSUE TITLE
stylesheet_syntax.md missing in repo

### ISSUE THREAD

**Issue by Wandmalfarbe** [ali-rantakari/peg-markdown-highlight#14]
I cant find the file `stylesheet_syntax.md` anywhere in the repo though it is mentioned in the readme.

**Comment by jakoch** [comment]
Hmm, maybe this one: https://github.com/ali-rantakari/peg-markdown-highlight/blob/master/stylesheet_syntax.md ?

**Comment by Wandmalfarbe** [comment]
Yes, that's the one.
