### ISSUE TITLE
pmh_parser.c file missing

### ISSUE THREAD

**Issue by dcutting** [ali-rantakari/peg-markdown-highlight#16]
Trying to build the Cocoa example but getting a build error because it can't find `pmh_parser.c`.

This is a symlink in the example_cocoa directory, but it doesn't resolve to any actual file.

Should there be a `pmh_parser.c` file in the root directory?

**Comment by ali-rantakari** [comment]
You need to generate that file with `make` first. Please see the readme for more information.

**Comment by dcutting** [comment]
Apologies, please ignore me, and thanks for some great software. :)
