### ISSUE TITLE
Spaces break link

### ISSUE THREAD

**Issue by tamlok** [ali-rantakari/peg-markdown-highlight#18]
If there are spaces in a link, that link won't be recognized as a link:

```
[github](http://some url may contain spaces)
```

Thanks very much!

**Comment by uranusjr** [comment]
[URLs aren’t supposed to contain spaces.](http://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space) They should be encoded into `%20`, in you case the markup should be

```
[github](http://some%20url%20may%20contain%20spaces)
```

Some Markdown parser does allow spaces and escape them automatically, but this is not the standard way, and is not portable. Is it better to escape manually. See [this Babelmark snippet](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5BText%5D(http%3A%2F%2Ffoo.com%2Fwith+space)) for comparison of results from various Markdown parsers.

**Comment by tamlok** [comment]
@uranusjr Got it! Thanks very much!
