### ISSUE TITLE
Footnotes with strong-emphasis take forever to highlight

### ISSUE THREAD

**Issue by uranusjr** [ali-rantakari/peg-markdown-highlight#6]
The following literally takes *seconds* of near-100% CPU to highlight in the Cocoa demo:

    First.[^1] Second.[^2] Third.[^3] Fourth.[^4] Fifth.[^5]
    
    [^1]: A ***B***
    [^2]: ***C***
    [^3]: ***D***
    [^4]: ***E***
    [^5]: ***F***

And it gets worse with every `***` blocks you have. I observed some curious behaviours:

* Only `***` markups matter. If you change any of the above `***`s into `**`, for example, the highlighting feels instant.
* If you take out the `A` in the first footnote, things will be fine.
* The magnitude of slowdown seems to be related with how many `***` blocks there are *after* the `A`. Say if you put the `A` before `***C***` things will improve a bit. But if you then add another footnote like `[^6]: ***G***` things will go bad again.

**Comment by ali-rantakari** [comment]
I took some time to look into this and was able to fix this issue by updating the grammar to match the current state of `peg-markdown`:

```
$ time ./old_tester testfiles/footnotes-slow.md >/dev/null

real	0m4.462s
user	0m4.407s
sys	0m0.031s
$
$ time ./tester testfiles/footnotes-slow.md >/dev/null

real	0m0.046s
user	0m0.015s
sys	0m0.011s
```

Thanks for the excellent bug report. Hopefully “better late than never” applies here.

**Comment by uranusjr** [comment]
Thank you!! This is still a huge problem in MacDown, and based on the download count, the fix will help probably hundreds of users. :smile:
